name: AlchemicalCauldron
main: com.circuitlocution.alchemicalcauldron.AlchemicalCauldron
version: 0.0.7.b
commands:
    recipes:
      description: Display a list of known alchemy recipes.
      usage: /<command>
